AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'

Metrics/BlockLength:
  Max: 30

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
