AllCops:
  Exclude:
    - 'bin/*'
    - 'node_modules/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
