language: ruby
rvm:
  - 2.6.3
services:
  - docker
before_install:
  - docker-compose build
  - docker-compose run todo_web bash -c "bundle exec foreman start;"
  # - docker run -d -p 127.0.0.1:80:4567 lp_todo /bin/sh -c "cd /app; bundle exec foreman start;"
  # - docker ps -a
  - docker-compose run todo_web bash -c "bundle exec rake db:create db:migrate;"
script:
  - docker-compose run todo_web bash -c "bundle exec rspec;"
