version: '3.1'
services:
  todo_web:
    build: .
    restart: always
    image: lp_todo_todo:latest
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
    links:
      - psql
    depends_on:
      - psql
  psql:
    image: postgres:11.4
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - psql_db:/var/lib/postgresql/data
volumes:
  psql_db:
    driver: local
