version: '3.1'
services:
  todo:
    build: .
  todo_web:
    restart: on-failure
    image: lp_todo_todo:latest
    env_file: .env
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RACK_ENV: development
    links:
      - psql
    depends_on:
      - psql
  psql:
    restart: on-failure
    image: postgres:12
    expose:
      - "5432"
    ports:
      - "5432"
    volumes:
      - psql_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=aqwe123
volumes:
  psql_db:
    driver: local
